#!/bin/sh

set -e

PREREQ="zfs"

prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

if grep zfs-yubikey-encrypt-root /proc/cmdline; then
    /usr/bin/zfs-yubikey-encrypt-root
fi
